### ISSUE TITLE
Aggregate notification when alert triggered for multiple validators

### ISSUE THREAD

**Issue by jchen86** [jchen86/staker-notifier#1]
Instead of sending a long sms with validator addresses, send an aggregate message when there are alerts for multiple validators, e.g. "x out of y of your validators have reduced balance since last epoch"

**Comment by yury-dubinin** [comment]
IMO, it is better to truncate validator key to say 6-8 characters so it is still possible to view specific validator in beaconcha.in or somewhere else.

**Comment by jchen86** [comment]
Agree - using validator index now so it's easily searchable on beaconcha.in.

**Comment by jchen86** [comment]
Message now looks like this:
"Sending SMS: 1 out of 2 validators have balance reduced since last epoch. Please check validator(s) 249002."
